name: Blog updates

on:
  push:
        branches:
        - main

env:
  AWS_REGION : "eu-west-1"

jobs: 

build_job : 

name: Build
runs_on: ubuntun-latest
steps: 
  - name: Checkout Repository
    uses: action/checkout@v4
    
  - name: Setup hugo
    uses: peaceiris/actions-hugo@v3
    with: 
     hugo-version: "latest" 
     extented: true

  - name: Build
    run: hugo

  - name: Upload Artifact
    uses: actions/upload-artifact@v4
    with:
     name: tech-blog
     path: public/*


deploy_job:
      name: Publish
      needs: [build_job]
      runs_on: ubuntun latest
      permissions:
        id-token: write
        contents: read


  steps: 

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with: 
          name: tech-blog

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
         role-to-assume: ${{ secrets.Role }}
         aws-region: ${{ env.AWS_REGION }}

       - name: S3 sync
         run: |
         aws s3 sync . s3://${{ secrets.BUCKET_NAME }} \ --delete

        - name: Create Cloudfront Invalidation
          run: | 
            aws cloud create-invalidation  \ 
            --distribution-id ${{ vars.DISTRIVUTION_ID }}  \
            --paths "/*"
       

        
