name: Sync to S3

on:
  push:
    branches:
      - main

jobs:
  sync-to-s3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Sync folder to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-west-1'          
          SOURCE_DIR: 'public/'              
          
